doc: instructions for joining and leaving the network as a validator
axelarnetwork/axelarate-community pull request #81
Opened 2021-06-16 08:39 UTC by Windforcer

2021-06-16 08:43 UTC, Windforcer commented
I will be around a few hours before the ceremony to implement any feedback

2021-06-16 18:05 UTC, cgorenflo approved these changes

2021-06-16 18:06 UTC, sergeynog requested changes

2021-06-16 18:09 UTC, cgorenflo commented on Exercises/excercise_3_join_leave_validator.md
> +  Here `amount` refers to the amount of coins to stake, with a minimum of 500,000 axltest. You can change the amount, but leave some coins on the account to fund commands.
correct

2021-06-16 19:23 UTC, Windforcer commented
Thanks for the comments, I've implemented the suggestions :)

2021-06-16 19:30 UTC, sergeynog commented on Exercises/excercise_3_join_leave_validator.md
> +  Here `amount` refers to the amount of coins to stake, with a minimum of 500,000 axltest. You can change the amount, but leave some coins on the account to fund commands.
following up on our offline discussion with Chris, we need `50000000` to become active for keygen/sign (10B is total supply). i would put that here. we'll update the faucet to distribute more. @Windforcer @cgorenflo

2021-06-16 20:38 UTC, Windforcer commented on Exercises/excercise_3_join_leave_validator.md
> +  Here `amount` refers to the amount of coins to stake, with a minimum of 500,000 axltest. You can change the amount, but leave some coins on the account to fund commands.
Staking amount increased by 10x in instructions

2021-06-21 12:11 UTC, sergeynog approved these changes

2021-06-21 12:11 UTC, merged